$ANSIBLE_VAULT;1.1;AES256
35383830343161393334613139326430303131656237643966346132303635343034363239363334
6233303633303262616434353163346564346431656432330a383136613366376338643865343432
62386339346563636566666339323464396635303639303665343462393463353030326361643831
6565616236386437390a313730616663323231633938663364313636656133306232383765323262
34353538353734663835313839633331663235626633303135303739336463343937363430643530
64396165653763363836626637323664383836343331343138303336613563626464633064363331
36373339663265653531333035373165346136313031393138336666376136616333656430366236
37623235373464326132633462666164306538373934356133383430393162653465383233373535
61353436363333643464313533343833333235326634323364306136646363336639653530633930
32316139396137366439343661636166353437306432653633653766313165633930656331666438
373135353431613633656666633934356432
