apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: amazona-ingress
  namespace: amazona
  annotations:
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /$1
    # Link to the ClusterIssuer
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    # Force the Redirect to HTTPS
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    # Basic Auth for Prometheus

spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - {{ .Values.ingress.app_host }}
    secretName: amazona-tls-secret
  rules:
  - host: {{ .Values.ingress.app_host }}
    http:
      paths:
      - path: /?(api/.*)
        pathType: ImplementationSpecific
        backend:
          service:
            name: backend-service
            port:
              number: 5000
      - path: /?(.*)
        pathType: ImplementationSpecific
        backend:
          service:
            name: frontend-service
            port:
              number: 80
      
