apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: amazona-ingress
  namespace: amazona
  annotations:
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /$1
    # Link to the ClusterIssuer
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    # Force the Redirect to HTTPS
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    # Basic Auth for Prometheus
    nginx.ingress.kubernetes.io/auth-type: "basic"
    nginx.ingress.kubernetes.io/auth-secret: "prometheus-basic-auth"
    nginx.ingress.kubernetes.io/auth-realm: "Protected Metrics"

spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - depiamazona.ddnsgeek.com  
    secretName: amazona-tls-secret
  rules:
  - host: depiamazona.ddnsgeek.com 
    http:
      paths:
      - path: /?(api/.*)
        pathType: ImplementationSpecific
        backend:
          service:
            name: backend-service
            port:
              number: 5000
      - path: /?(.*)
        pathType: ImplementationSpecific
        backend:
          service:
            name: frontend-service
            port:
              number: 80
  - host: monitoring.example.com
    http:
      paths:
        - path: /prometheus/?(.*)
          pathType: ImplementationSpecific
          backend:
            service:
              name: prometheus-service
              port:
                number: 9090
        - path: /grafana/?(.*)
          pathType: ImplementationSpecific
          backend:
            service:
              name: grafana-service
              port:
                number: 3000
      

