apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: amazona-ingress-monitoring
  namespace: amazona
  annotations:
    # Link to the ClusterIssuer
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    # Force the Redirect to HTTPS
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    # Basic Auth for Prometheus & Grafana
    nginx.ingress.kubernetes.io/auth-type: "basic"
    nginx.ingress.kubernetes.io/auth-secret: "prometheus-basic-auth"
    nginx.ingress.kubernetes.io/auth-realm: "Protected Metrics"

spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - {{ .Values.ingress.app_monitor }}
    secretName: monitoring-tls-secret
  rules:
  - host: {{ .Values.ingress.app_monitor }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: prometheus-service
            port:
              number: 9090
      - path: /grafana
        pathType: Prefix
        backend:
          service:
            name: grafana-service
            port:
              number: 3000

