backend:
  image: "depi-app-backend:latest"
  replicas: 2
  port: 5000

frontend:
  image: "depi-app-frontend:latest"
  replicas: 2
  port: 80

secrets:
  AWS_ACCESS_KEY: ""
  AWS_SECRET_KEY: ""
  JWT_TOKEN: ""
  DB_USER: ""
  DB_PASS: ""

config:
  bucketName: "default-bucket"
  region: "us-east-1"
